var langue = ({
    fr:{
        accueil : "Accueil" ,
        technique : "Techniques",
        doc : "Documentation",
        climat : "Climats",
        region : "Regions",
        carte : "Carte",
        plante : "Plantes",
        titre1 : "Sauvons l'Agriculture ",
        titre2 : "par les Innovations techniques",
        sous_titre : "Concours afass hackathon",
        onglet1 : "Agriculture",
        onglet1_description : "Art d'obtenir du sol tout en minimisant l'effort physique et les dépense financières et en maximisant le profit.",
        onglet2 : "Climat",
        onglet2_description : "situation atmosphérique qui présente à un moment determiné et qui dépendra de divers facteurs tels précipitations, température, pression,...",
        onglet3 : "Techniques",
        onglet3_description : "ensemble des opérations successives aboutissant à un résultat",
        onglet4 : "système de production",
        onglet4_description : "Une forte interaction entre agriculture, climat et technique pour parvenir à un but.",
        connaissance : "Avant-propos",
        mada : "Madagascar",        
        description_connaissance :"Depuis quelques décennies, le changement climatique s’aggrave et présente des effets néfastes. Cela reflète sur les phénomènes météorologiques, l’épuisement des ressources naturelles et sur l’agriculture. Cette dernière menace le monde à l’égard de la pression démographique élevée. Environ 0,5 % de terres arables à Madagascar sont disparues chaque année. Ce contexte incite la curiosité des jeunes développeurs et élève ingénieur agronome promoteurs de développement, à chercher des alternatives pour pouvoir éradiquer la destruction de la nature.",
        description_technique : "Les techniques agricoles intelligentes face au climat peuvent augmenter la productivité agricole et les revenus, rendre les communautés rurales plus résilientes au changement climatique et si possible, atténuer le changement climatique.",
        gallerie : 'GALLERIE',
        afficher_plus:'Afficher plus',
        tout:'Tout',
        contacter : "Contactez-nous" ,
        nom : "Nom",
        prenom : "Prénoms",
        email : "Email" ,
        telephone : "Téléphone",
        Objet : "Objet",
        message : "Message",
        envoyer : "Envoyez",
        liens : "Liens" ,
        a_propos : "Devenir un vulgarisateur",
        rechercher : "Rechercher",
        nous_contacter : "Nous contacter",
        copyright : "Copyright © 2021 Tanimboly. Tous droits réservés.",
        help :"Comment pouvons-nous vous aider?",
        list_technique :"Liste des techniques :",
        list_plante : "Liste des plantes :",
        list_region : "Liste des régions :",
        liste_climat : "Liste des climats :",
        description_region : "Madagascar est une grande île ayant une superficie 587 041 km². De Nord au Sud et Est au Ouest, de plusieurs différences s’observent. Les zones Nord-est, Est et Sud-est présentent des caractéristiques du sol et conditions climatiques semblables. Les cultures d’exportations y prédominent. Les zones ouest et Sud-ouest ont également des traits communs et qui sont favorables aux cultures industrielles. En particulier, la zone sud-est victime de la sécheresse dont la précipitation annuelle est très faible. Et le reste, c’est-à-dire la partie haute-terre est douée de la culture des légumineuses grâce aux propriétés physico-chimiques de ses sols.",
        titre_1_bloc :"Page Accueil " ,
        sous_titre_1_bloc :"" ,
        description_1_bloc :"Dans la première page, vous pourriez apercevoir une barre de recherche qui vous aidera à rechercher parmi nos techniques selon les régions. Vous pourriez également nous envoyer directement un e-mail, ou via nos contacts et réseaux sociaux en bas de la page." ,
        finalisation_1_bloc :"Si vous voulez devenir un de vulgarisateur, vous pourriez créer un compte, et vous pourriez aussi nous proposer des nouvelles techniques qu'on va encore vérifier." ,
        titre_2_bloc :"Page Technique" ,
        sous_titre_2_bloc :"" ,
        description_2_bloc :"Dans cette page, il y aura la liste de toutes les techniques qu'on a sur notre base de données, bien sûr, vous pourriez aussi proposer d'autres en créant un compte vulgarisateur. Vous n'avez pas cliqué sur un des techniques en savoir un peu plus comme les étapes, les matériels, et aussi des liens externes pour vous donner plus d'information sur la technique en particulier." ,
        finalisation_2_bloc :"Pour vous faciliter la navigation sur le site, vous pourriez directement taper sur la barrer des tâches." ,
        titre_3_bloc :"Page CARTE" ,
        sous_titre_3_bloc :"" ,
        description_3_bloc :"Sur cette page, il y aura une carte de Madagascar avec ses 22 régions sur lesquelles on pourra aussi cliquer, qui nous redirigera directement sur les détails de la région comme le type, la structure du sol, le climat qu'il y a, les plantes qui s'adapteront parfaitement dans ce genre terrains, mais surtout les techniques à savoir pour nos cultivateurs." ,
        finalisation_3_bloc :"" ,
        titre_4_bloc :"Page plantes" ,
        infos : "Plus d'information:",
        sous_titre_4_bloc :"" ,
        description_4_bloc :"Dans cette page, vous pourriez consulter toutes les différentes plantes qui sont cultivées à Madagascar. Vous n'avez qu'à cliquer sur l'un d'eux pour en savoir plus d'informations, comme tous les critères ses exigences pendant son stade phénologique lumière, température, humidité, on vous propose également les nouvelles techniques AIC qui pourraient améliorer sa culture." ,
        finalisation_5_bloc :"" ,
        titre_5_bloc :"UN BONUS" ,
        sous_titre_5_bloc :" Comment devenir un 'Vulgarisateur' ?" ,
        description_5_bloc :"Comme on ne pourrait pas remplir tout seul les données , le paysans , vulgarisateurs,les agriculteurs ,...tout le monde pourra ajouter  des informations,juste que les informations doivent d'abord passer un série de vérifation. " ,
        climat_rel :" Climats adaptés :",
        region_rel :" Régions adaptées :" ,
        plante_rel :"Plantes adaptées :",
        tech_rel :" Techniques adaptées :",
        type_sol :" Type du sol",
        struct_sol :"Structure du sol",
        text_sol :"Texture du sol",
        voir:'Voir Région',
        lumiere:'Lumière',
        humidite:'Humidité',
        floraison:'Floraison',
        temperature:'Température',
        description:'Description',
        genre:'Genre',
        regne:'Règne',
        ordre:'Ordre',
        espece:'Espèce',
        embranchement:'Embranchement',
        famille:'Famille',
        classe : "Classe",
        login:'Se connecter',
        agriculture_tec:"Agriculture",
        climato_tec: "Climato",
        intelligente_tec:"Intelligente",
        eau_tec: "Eau",
        productivite:"Productivité",
        adaptation:"Adaptation",
        mitigation:"Mitigation",
        description_tec:"Description",
        materiels_tec:"Matériels",
        etapes_tec:"Étapes ",
        plante_tec:"Plantes adaptées ",
        climats_tec:"Climats adaptés",
        regions_tec:"Régions adaptées",
        email_log:"Email",
        mot_de_passe_log:"Mot de passe",
        bienvenue: "Bienvenue à tous",
        creer_un_compte:"Créer un compte",
        nouveu:'Nouveau compte',
        appelation:'Appelation',
        conf:'Confirmation de mot passe',
        type_compte:'Type de compte',
        visite:'Visiter',
        nom_science : "Nom scientifique",
        sponsor:'SPONSORS'
    },
    mg:{
        nom_science : "Anarana siantifika",
        visite:'Hitsidika',
        tech_rel :" Tekinika azo ampiharina :",
        lumiere:'Hazavana',
        humidite:'Hamandoana',
        floraison:'Fitsimoana',
        temperature:'Hafanana',
        description:'Mombamomba',
        genre:'Karazana',
        help :"Ahoana no ahafahanay manampy anao?",
        infos : "Fanazavana fanampiny :",
        regne:'Vondrona',
        ordre:'Sokajy',
        espece:'Taranaka',
        embranchement:'Fizarana',
        famille:'Fianakaviana',
        accueil : "Fandraisana" ,
        technique : "Teknika",
        region : "Faritra",
        mada : "Madagasikara",
        climat : "Toe-tany",
        carte : "Sarintany", 
        doc : "Fampahafantarana",
        plante : "Zava-maniry",
        titre1 : "Andao avotana ny fambolena",
        titre2 : "amin'ny alalan'ny fanavaozana ara-teknika.",
        sous_titre : "Concours afass hackathon",
        onglet1 : "Famokarana",
        onglet1_description : "Karazana hai-tao izay mikatsaka ny hampihena ny ezaka ara-batana sy ny fandaniana ara-bola ary ny mampiakatra ny tombom-barotra.",
        onglet2 : "Toe-tany",
        onglet2_description : "Toe-javatra iainana izay maneho amin'ny fotoana voatondro izay hiankina amin'ny anton-javatra na masontsivana isan-  karazany (mari-pana, rotsakorana).",
        onglet3 : "Teknika",
        onglet3_description : "Fitambaran'ireo fomba ampiasaina hamokarana asa na hahazoana valiny voafaritra.",
        onglet4 : "Rafitra", 
        onglet4_description : "Fifandraisana matanjaka eo amin'ny fambolena sy ny toetrandro ary ny teknolojia hahatratrarana tanjona iray.",
        connaissance : "Voalohany",
        description_connaissance :"Tao anatin'izay folo taona lasa izay dia niharatsy ny fiovan'ny toetrandro ary nisy fiatraikany ratsy. Hita taratra izany amin'ny fisehoan-toetr'andro, ny fihenan'ny harena voajanahary ary ny fambolena. Ity farany dia mandrahona izao tontolo izao amin'ny resaka tsindry hazon'ny mponina. Manodidina ny 0,5% ny tany azo volena eto Madagasikara no very isan-taona. Mampientanentana ny fahalianan'ny tanora mpamorona sy mpampiroborobo ny fampandrosoana ny injeniera momba ny fambolena ity toe-javatra ity, hikatsahana safidy hafa hahafahana mamongotra ny fanimbana ny natiora." ,
        gallerie : 'SARY',
        afficher_plus:'Manaraka',
        tout:'Rehetra',
        contacter : "Hiresaka aminay" ,
        nom : "Anarana",
        prenom : "Fanampin'anarana",
        email : "Mailaka" ,
        telephone : "Laharana finday",
        Objet : "Zavatra",
        message : "Hafatra",
        voir:'Hijery Faritra',
        envoyer : "Alefa",
        liens : "Rohy" ,
        a_propos : "Mombamomba anay",
        rechercher : "Hitady",
        nous_contacter : "Hiresaka aminay",
        copyright : "Copyright © 2021 Tanimboly. Tous droits réserves.",
        list_technique :"Lisitr'ireo tekinika :",
        list_plante : "Lisitr'ireo zava-maniry :",
        list_region : "Lisitr'ireo faritra :",
        liste_climat : "Lisitr'ireo toe-tany :",
        description_region : "Nosy lehibe i Madagasikara manana velarana 587.041 km². Avy Avaratra ka hatrany atsimo ary atsinanana mankany andrefana, misy fahasamihafana maro. Ny faritra Avaratra Atsinanana, Atsinanana ary atsimo-Atsinanana dia manana toetra mampiavaka ny tany sy ny toetr'andro. Ny voly fanondranana no tena mibahantoerana. Ny faritra andrefana sy atsimo andrefana dia manana mahasamihafa azy ihany koa izay mety amin’ny voly indostrialy. Manokana, ny faritra atsimo dia iharan'ny haintany, ary ambany dia ambany ny rotsakorana isan-taona. Ary ny ambiny dia ny fambolena legioma no tena mety aminy noho ny fananana fizikokimia an'ny tany." ,
        titre_1_bloc :"Pejy 'FANDRAISANA'" ,
        sous_titre_1_bloc :"" ,
        description_1_bloc :"Ao amin'ny pejy FANDRAISANA dia afaka manao fitadiavana teknika na faritra amin'ny alalan'ny teny iray eo amin'ny saha 'Hitady'. Eo ambany dia misy santionana teknika izay afaka tsindrina dia mivoaka ny momba azy. Afaka manoratra ho aty aminay koa ianareo eo amin'ny saha 'Hiresaka aminay'" ,
        finalisation_1_bloc :"Eny amin'ny tongotry ny pejy dia ahitana ny momba anay toy ny laharan'tarombia, mailaka, tambazotra tserasera" ,
        titre_2_bloc :"Pejy TEKNIKA" ,
        sous_titre_2_bloc :"" ,
        description_2_bloc :"Ao amin'ny pejy TEKNIKA dia ahitana ireo lisitra teknika izay misy ao anatin'ny tranonkala tanimboly.org. Miseho eo alohan'ny sary ny lohatenin'ilay teknika ahafantarana azy mialoha. Ra hijery ny momban'ny teknika iray de tsindrina ilay teknika ka hisokatra manaraka izay ny momba azy" ,
        finalisation_2_bloc :"Misy saha fitadiavana ihany koa etsy ambonin'ireo lisitra ahafahana mitady teknika na faritra na zava-maniry na ireo rehetra ireo miaraka" ,
        titre_3_bloc :"Pejy SARINTANY" ,
        sous_titre_3_bloc :"" ,
        description_3_bloc :"Ao amin'ny pejy SARINTANY dia misy sarin'i Madagasikara ahitana ireo faritra 22 miaraka amin'ny endrik'izy reo tsirairay avy. Afaka manindry faritra iray ahitana ny momba azy sy ny tekinika, toe-tany ary zava-maniry mifandraika aminy. Afaka manoratra ny faritra tadiavina manokana koa eo amin'ny saha 'Hijery faritra' " ,
        finalisation_3_bloc :"" ,
        titre_4_bloc :"Pejy ZAVA-MANIRY" ,
        sous_titre_4_bloc :"" ,
        description_4_bloc :"Pejy ZAVA-MANIRY dia ahitana ireo lisitry ny zava-maniry misy ao amin'ny tranonkala tanimboly.org. Raha te hijery ny zava-maniry hafa dia tsindrio ny 'Manaraka'. Raha te hahita ny momban'ny zava-maniry iray dia tsindrio ny zava-maniry araka ny safidinao ka hisokatra manaraka izay ny momba azy" ,
        finalisation_5_bloc :"" ,
        titre_5_bloc :"Pejy TOE-TANY" ,
        sous_titre_5_bloc :"" ,
        description_5_bloc :"Ao amin'ny pejy TOE-TANY dia ahitana ireo karazana toe-tany misy eto Madagasikara sy ireo mombamomba azy tsirairay avy" ,
        climat_rel : "Toe-tany mety :",
        region_rel : "Faritra mety :" ,
        plante_rel : "Zava-maniry mety",
        type_sol :" Karazana tany",
        struct_sol :" Firafitry ny tany",
        text_sol :"Volavolan-tany ",
        login:'Hiditra',
        agriculture_tec:"Fambolena",
        climato_tec: "Toe-tany",
        intelligente_tec:"Manarapenitra",
        eau_tec: "Rano",
        productivite:"Famokarana",
        adaptation:"Fampifanarahana",
        mitigation:"Fanalefahana",
        description_tec:"Famaritana",
        materiels_tec:"Fitaovana ",
        etapes_tec:"Dingana",
        plante_tec:"Zava-maniry mety",
        climats_tec:"Toe-tany mety",
        regions_tec:"Faritra mety",
        email_log:"Mailaka",
        mot_de_passe_log:"Teny miafina",
        bienvenue: "Tongasoa",
        creer_un_compte:"Hamorona kaonty",
        nouveu:'Kaonty vaovao',
        appelation:'Fiantsoana',
        conf:'Fanamarinana teny miafina',
        type_compte:'Karazana kaonty',
        classe : "Kilasy",
        sponsor:'MPANOHANA'
    }
})
export default langue
